#!/usr/bin/env python3
"""
Bemal - Simple Working Flask Server
No complex dependencies, just a working GUI
"""

import os
from flask import Flask, render_template, request, jsonify
from flask_sqlalchemy import SQLAlchemy
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__, template_folder='templates', static_folder='static')
app.secret_key = os.getenv('SECRET_KEY', os.urandom(24))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///users.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['UPLOAD_FOLDER'] = 'uploads'

db = SQLAlchemy(app)
os.makedirs('uploads', exist_ok=True)

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/dashboard')
def dashboard():
    return render_template('dashboard.html')

@app.route('/login')
def login():
    return render_template('login.html')

@app.route('/generate', methods=['POST'])
def generate():
    """Mock email generation"""
    data = request.json
    name = data.get('name', 'Unknown')
    company = data.get('company', 'Unknown')
    role = data.get('role', 'Unknown')
    
    email = f"""Subject: Quick question about {company}

Hi {name},

I noticed you're the {role} at {company} and wanted to reach out.

We've been helping companies like {company} streamline their operations and reduce costs by 30%.

Would you be open to a quick 15-minute chat next week?

Best regards,
Your Team

---
This email was generated by Bemal AI"""

    return jsonify({'success': True, 'email': email})

@app.route('/upload', methods=['POST'])
def upload():
    """Mock CSV processing"""
    return jsonify({
        'success': True,
        'results': [
            {'name': 'Test User', 'company': 'Test Corp', 'status': 'success', 'generated_email': 'Test email content...'}
        ]
    })

if __name__ == '__main__':
    print("🚀 Bemal Server starting...")
    print("📍 Open http://localhost:5000")
    app.run(debug=True, host='0.0.0.0', port=5000)
