#!/usr/bin/env python3
"""
Bemal - Setup Wizard
Interactive setup for email configuration
"""

import os
import sys
from pathlib import Path

ENV_FILE = Path('.env')

def print_banner():
    print("""
    ╔════════════════════════════════════════════════╗
    ║  🚀 Bemal - AI Email Outreach Setup Wizard    ║
    ║  Configure your email settings                 ║
    ╚════════════════════════════════════════════════╝
    """)

def ask_question(question, default=None, required=False):
    """Ask a question and get user input"""
    if default:
        prompt = f"{question} [{default}]: "
    else:
        prompt = f"{question}: "
    
    while True:
        answer = input(prompt).strip()
        if not answer:
            if default:
                return default
            if required:
                print("❌ This field is required!")
                continue
        return answer if answer else default

def main():
    print_banner()
    
    print("\n📧 Email Configuration")
    print("-" * 40)
    
    # Get email settings
    email_address = ask_question(
        "Email address (Gmail recommended)",
        required=True
    )
    
    print("\n🔐 For Gmail:")
    print("1. Go to: https://myaccount.google.com/security")
    print("2. Enable 2-Factor Authentication")
    print("3. Generate App Password: https://myaccount.google.com/apppasswords")
    print("4. Use the 16-character password (no spaces)")
    
    email_password = ask_question(
        "\nApp Password (or regular password)",
        required=True
    )
    
    print("\n📤 SMTP Settings")
    print("-" * 40)
    
    smtp_server = ask_question(
        "SMTP Server",
        default="smtp.gmail.com"
    )
    
    smtp_port = ask_question(
        "SMTP Port",
        default="587"
    )
    
    print("\n✅ Configuration Summary")
    print("-" * 40)
    print(f"Email: {email_address}")
    print(f"SMTP Server: {smtp_server}")
    print(f"SMTP Port: {smtp_port}")
    print()
    
    confirm = input("Save this configuration? (y/n): ").strip().lower()
    if confirm != 'y':
        print("❌ Configuration cancelled")
        return
    
    # Create .env file
    env_content = f"""# Bemal AI Email Outreach - Configuration
# Generated by setup wizard

# Security
SECRET_KEY={os.urandom(24).hex()}

# Email Configuration
EMAIL_ADDRESS={email_address}
EMAIL_PASSWORD={email_password}
SMTP_SERVER={smtp_server}
SMTP_PORT={smtp_port}
SMTP_USE_TLS=true
SMTP_USE_SSL=false
SMTP_TIMEOUT=10

# Database
DATABASE_URL=sqlite:///bemal.db

# Optional: Custom SMTP settings
# SMTP_USE_TLS=true
# SMTP_USE_SSL=false
# SMTP_TIMEOUT=10
"""
    
    with open(ENV_FILE, 'w') as f:
        f.write(env_content)
    
    print("\n✅ Configuration saved to .env")
    print("\n🎯 Next steps:")
    print("1. Run: python server.py")
    print("2. Open: http://localhost:5000")
    print("3. Start sending emails!")
    print()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled")
        sys.exit(1)
